"""Add new column to User and create Appointment table

Revision ID: 38e69d481ffc
Revises: cfd67cc3ad02
Create Date: 2024-05-26 12:22:48.587396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e69d481ffc'
down_revision = 'cfd67cc3ad02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=False),
    sa.Column('additional_notes', sa.String(length=500), nullable=True),
    sa.Column('appointment_date', sa.DateTime(), nullable=False),
    sa.Column('customer_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['customer_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    op.drop_table('appointment')
    # ### end Alembic commands ###
